apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    name: flask-app
  namespace: cloudnat
spec:
  replicas: 1
  selector:
    matchLabels:
      name: flask-app
  template:
    metadata:
      name: flask-app
      labels:
        name: flask-app
    spec:
      containers:
        - name: flask-app
          image: us-central1-docker.pkg.dev/<<project-id>>/staticiptest/gkestaticip:v1
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 512Mi
          env:
            - name: PORT
              value: "8080"
            - name: DEBUG_MODE
              value: "1"
