apiVersion: v1
kind: Service
metadata:
  labels:
    name: flask-app
  name: flask-app
  namespace: cloudnat
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    name: flask-app
  sessionAffinity: None
  type: LoadBalancer